import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import NavButtons from "~/components/navbuttons";
import { IoPersonAddSharp } from "react-icons/io5";
import { useState } from "react";
import { TbRefresh } from "react-icons/tb";
import { Feed } from ".";

const Home: NextPage = () => {
  const { isLoaded: userLoaded, user } = useUser();

  const [selectedTab, setSelectedTab] = useState<
    "tweets" | "replies" | "media" | "likes"
  >("tweets");

  // Start fetching asap
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col">
        <div className="flex flex-col border-slate-400 pt-16">
          <img
            src="https://i.pinimg.com/originals/4d/d5/85/4dd585d3e8a1a6b23f9a54e5a1076c8b.jpg"
            alt="Picture of the author"
            className=" h-44 w-full object-cover md:h-96"
          />

          {/* profile box */}
          <div className="relative mx-4 -mt-4 flex h-64 flex-col items-center justify-center gap-y-2 rounded-xl bg-white pt-16">
            <img
              src={user?.profileImageUrl}
              alt="Picture of the author"
              className="absolute -top-16 left-0 right-0 m-auto aspect-square h-32 w-32 rounded-xl border-2 border-white object-cover  md:h-96"
            />
            <h1 className="text-2xl font-bold">{user?.fullName}</h1>
            <div className="flex w-full justify-evenly">
              <div className="flex gap-x-1 text-sm text-gray-500">
                <span className="font-bold text-black">2,569</span>Following
              </div>
              <div className="flex gap-x-1 text-sm text-gray-500">
                <span className="font-bold text-black">10.8k</span>Followers
              </div>
            </div>
            <div className="text-lg text-gray-500">
              Photographer & Filmmaker based in Copenhagen, Denmark ✵ 🇩🇰
            </div>
            <div className="flex items-center rounded-md bg-blue-500 px-4 py-1 text-sm text-white">
              <IoPersonAddSharp className="mr-2 inline-block" />
              <div>Follow</div>
            </div>
          </div>
          {/* end profile box */}

          {/* tweets/replies/media/likes */}

          <ul className="mx-4 mt-4 flex flex-col rounded-xl bg-white">
            <li
              className={`relative flex-1 px-6 py-4 text-sm font-medium text-gray-500 ${
                selectedTab === "tweets" && "text-blue-500"
              } `}
              onClick={() => setSelectedTab("tweets")}
            >
              <div
                className={`absolute left-0 h-1/2 w-1 rounded-r-xl ${
                  selectedTab === "tweets" ? "bg-blue-500" : "hidden"
                } `}
              ></div>
              Tweets
            </li>
            <li
              className={`relative flex-1 px-6 py-4 text-sm font-medium text-gray-500 ${
                selectedTab === "replies" && "text-blue-500"
              } `}
              onClick={() => setSelectedTab("replies")}
            >
              <div
                className={`absolute left-0 h-1/2 w-1 rounded-r-xl ${
                  selectedTab === "replies" ? "bg-blue-500" : "hidden"
                } `}
              ></div>
              Tweets & replies
            </li>
            <li
              className={`relative flex-1 px-6 py-4 text-sm font-medium text-gray-500 ${
                selectedTab === "media" && "text-blue-500"
              } `}
              onClick={() => setSelectedTab("media")}
            >
              <div
                className={`absolute left-0 h-1/2 w-1 rounded-r-xl ${
                  selectedTab === "media" ? "bg-blue-500" : "hidden"
                } `}
              ></div>
              Media
            </li>
            <li
              className={`relative flex-1 px-6 py-4 text-sm font-medium text-gray-500 ${
                selectedTab === "likes" && "text-blue-500"
              } `}
              onClick={() => setSelectedTab("likes")}
            >
              <div
                className={`absolute left-0 h-1/2 w-1 rounded-r-xl ${
                  selectedTab === "likes" ? "bg-blue-500" : "hidden"
                } `}
              ></div>
              Likes
            </li>
          </ul>
          {/* end tweets/replies/media/likes */}

          <div className="flex items-center p-4 text-sm ">
            <TbRefresh className="mr-1 text-gray-500" />
            <div className="text-center text-gray-500">
              {user?.fullName} retweeted
            </div>
          </div>
        </div>
        <div className="px-4">
          <Feed />
        </div>

        {/* push all the way down and keep there even on scroll */}
        <div className="fixed bottom-0 left-0 w-full md:hidden">
          <NavButtons />
        </div>
      </main>
    </>
  );
};

export default Home;
